### PR TITLE
Zone

### PR DESCRIPTION
**Pull request by a544266477**
implemented the zone and alternatives

### CODE REVIEW

**Review by cycomachead — CHANGES_REQUESTED** [review]
Lots of code here. 

This looks good overall. 
I'll merge this after one fix. Two things I'd just like to mention:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
This will save you a bunch of time and effort in the future

The bigger fix: The SQL query with like has a potential vulnerability. You still want to escape the parameter passed in:
https://guides.rubyonrails.org/active_record_querying.html#conditions-that-use-like
but that should be an easy fix. :)

**Comment by cycomachead** [comment]
Also, please resolve the conflicts before we can merge. :)

**Comment by a544266477** [comment]
Fernanda still working on the conflicts, we decide to first merge the changes of zone to golden repo first, then Fernanda will merge her changes and resolve it.

**Comment by cycomachead** [comment]
We can merge this until you resolve the changes with the main branch.

**Comment by a544266477** [comment]
Please review the new changes. I had merge the conflicts.

**Pull request merged**
